DROP TABLE IF EXISTS CLIENTE;
DROP TABLE IF EXISTS TRANSACAO_TABLE;
  
CREATE TABLE CLIENTE (
  card LONG PRIMARY KEY,
  pass_card VARCHAR(250) NOT NULL,
  balance_card DOUBLE NOT NULL
);

CREATE TABLE TRANSACAO_TABLE (
	ID VARCHAR(250) PRIMARY KEY,
	NUM_CARD LONG NOT NULL,
	VALUE DOUBLE NOT NULL,
	TYPE INT NOT NULL 
);